<?php
/**
 * ForwardApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Liara Mail API Documentaion
 *
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@liara.ir
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ForwardApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ForwardApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAddressForwarding' => [
            'application/json',
        ],
        'deleteExtraEndpoint' => [
            'application/json',
        ],
        'getListAddressForwarding' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAddressForwarding
     *
     * add address endpoint to forwarding mails
     *
     * @param  string $mail_server_id mail_server_id (required)
     * @param  string $account_id account_id (required)
     * @param  \OpenAPI\Client\Model\Model6 $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressForwarding'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\PostMails201Response
     */
    public function createAddressForwarding($mail_server_id, $account_id, $body = null, string $contentType = self::contentTypes['createAddressForwarding'][0])
    {
        list($response) = $this->createAddressForwardingWithHttpInfo($mail_server_id, $account_id, $body, $contentType);
        return $response;
    }

    /**
     * Operation createAddressForwardingWithHttpInfo
     *
     * add address endpoint to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  \OpenAPI\Client\Model\Model6 $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressForwarding'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\PostMails201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAddressForwardingWithHttpInfo($mail_server_id, $account_id, $body = null, string $contentType = self::contentTypes['createAddressForwarding'][0])
    {
        $request = $this->createAddressForwardingRequest($mail_server_id, $account_id, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\PostMails201Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\PostMails201Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\PostMails201Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\PostMails201Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PostMails201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createAddressForwardingAsync
     *
     * add address endpoint to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  \OpenAPI\Client\Model\Model6 $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressForwardingAsync($mail_server_id, $account_id, $body = null, string $contentType = self::contentTypes['createAddressForwarding'][0])
    {
        return $this->createAddressForwardingAsyncWithHttpInfo($mail_server_id, $account_id, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAddressForwardingAsyncWithHttpInfo
     *
     * add address endpoint to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  \OpenAPI\Client\Model\Model6 $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressForwardingAsyncWithHttpInfo($mail_server_id, $account_id, $body = null, string $contentType = self::contentTypes['createAddressForwarding'][0])
    {
        $returnType = '\OpenAPI\Client\Model\PostMails201Response';
        $request = $this->createAddressForwardingRequest($mail_server_id, $account_id, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAddressForwarding'
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  \OpenAPI\Client\Model\Model6 $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAddressForwardingRequest($mail_server_id, $account_id, $body = null, string $contentType = self::contentTypes['createAddressForwarding'][0])
    {

        // verify the required parameter 'mail_server_id' is set
        if ($mail_server_id === null || (is_array($mail_server_id) && count($mail_server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mail_server_id when calling createAddressForwarding'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $mail_server_id)) {
            throw new \InvalidArgumentException("invalid value for \"mail_server_id\" when calling ForwardApi.createAddressForwarding, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling createAddressForwarding'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $account_id)) {
            throw new \InvalidArgumentException("invalid value for \"account_id\" when calling ForwardApi.createAddressForwarding, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        


        $resourcePath = '/api/v1/mails/{mailServerID}/accounts/{accountID}/forwards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($mail_server_id !== null) {
            $resourcePath = str_replace(
                '{' . 'mailServerID' . '}',
                ObjectSerializer::toPathValue($mail_server_id),
                $resourcePath
            );
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteExtraEndpoint
     *
     * delete extra endpoint address
     *
     * @param  string $mail_server_id mail_server_id (required)
     * @param  string $account_id account_id (required)
     * @param  string $address_id address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteExtraEndpoint'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteExtraEndpoint($mail_server_id, $account_id, $address_id, string $contentType = self::contentTypes['deleteExtraEndpoint'][0])
    {
        $this->deleteExtraEndpointWithHttpInfo($mail_server_id, $account_id, $address_id, $contentType);
    }

    /**
     * Operation deleteExtraEndpointWithHttpInfo
     *
     * delete extra endpoint address
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteExtraEndpoint'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteExtraEndpointWithHttpInfo($mail_server_id, $account_id, $address_id, string $contentType = self::contentTypes['deleteExtraEndpoint'][0])
    {
        $request = $this->deleteExtraEndpointRequest($mail_server_id, $account_id, $address_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteExtraEndpointAsync
     *
     * delete extra endpoint address
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteExtraEndpoint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteExtraEndpointAsync($mail_server_id, $account_id, $address_id, string $contentType = self::contentTypes['deleteExtraEndpoint'][0])
    {
        return $this->deleteExtraEndpointAsyncWithHttpInfo($mail_server_id, $account_id, $address_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteExtraEndpointAsyncWithHttpInfo
     *
     * delete extra endpoint address
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteExtraEndpoint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteExtraEndpointAsyncWithHttpInfo($mail_server_id, $account_id, $address_id, string $contentType = self::contentTypes['deleteExtraEndpoint'][0])
    {
        $returnType = '';
        $request = $this->deleteExtraEndpointRequest($mail_server_id, $account_id, $address_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteExtraEndpoint'
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteExtraEndpoint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteExtraEndpointRequest($mail_server_id, $account_id, $address_id, string $contentType = self::contentTypes['deleteExtraEndpoint'][0])
    {

        // verify the required parameter 'mail_server_id' is set
        if ($mail_server_id === null || (is_array($mail_server_id) && count($mail_server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mail_server_id when calling deleteExtraEndpoint'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $mail_server_id)) {
            throw new \InvalidArgumentException("invalid value for \"mail_server_id\" when calling ForwardApi.deleteExtraEndpoint, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling deleteExtraEndpoint'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $account_id)) {
            throw new \InvalidArgumentException("invalid value for \"account_id\" when calling ForwardApi.deleteExtraEndpoint, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        
        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling deleteExtraEndpoint'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $address_id)) {
            throw new \InvalidArgumentException("invalid value for \"address_id\" when calling ForwardApi.deleteExtraEndpoint, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        

        $resourcePath = '/api/v1/mails/{mailServerID}/accounts/{accountID}/forwards/{addressID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($mail_server_id !== null) {
            $resourcePath = str_replace(
                '{' . 'mailServerID' . '}',
                ObjectSerializer::toPathValue($mail_server_id),
                $resourcePath
            );
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }
        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'addressID' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getListAddressForwarding
     *
     * get all extra address to forwarding mails
     *
     * @param  string $mail_server_id mail_server_id (required)
     * @param  string $account_id account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getListAddressForwarding'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\MailForwards
     */
    public function getListAddressForwarding($mail_server_id, $account_id, string $contentType = self::contentTypes['getListAddressForwarding'][0])
    {
        list($response) = $this->getListAddressForwardingWithHttpInfo($mail_server_id, $account_id, $contentType);
        return $response;
    }

    /**
     * Operation getListAddressForwardingWithHttpInfo
     *
     * get all extra address to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getListAddressForwarding'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\MailForwards, HTTP status code, HTTP response headers (array of strings)
     */
    public function getListAddressForwardingWithHttpInfo($mail_server_id, $account_id, string $contentType = self::contentTypes['getListAddressForwarding'][0])
    {
        $request = $this->getListAddressForwardingRequest($mail_server_id, $account_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\MailForwards' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\MailForwards' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\MailForwards', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\MailForwards';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\MailForwards',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getListAddressForwardingAsync
     *
     * get all extra address to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getListAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getListAddressForwardingAsync($mail_server_id, $account_id, string $contentType = self::contentTypes['getListAddressForwarding'][0])
    {
        return $this->getListAddressForwardingAsyncWithHttpInfo($mail_server_id, $account_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getListAddressForwardingAsyncWithHttpInfo
     *
     * get all extra address to forwarding mails
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getListAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getListAddressForwardingAsyncWithHttpInfo($mail_server_id, $account_id, string $contentType = self::contentTypes['getListAddressForwarding'][0])
    {
        $returnType = '\OpenAPI\Client\Model\MailForwards';
        $request = $this->getListAddressForwardingRequest($mail_server_id, $account_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getListAddressForwarding'
     *
     * @param  string $mail_server_id (required)
     * @param  string $account_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getListAddressForwarding'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getListAddressForwardingRequest($mail_server_id, $account_id, string $contentType = self::contentTypes['getListAddressForwarding'][0])
    {

        // verify the required parameter 'mail_server_id' is set
        if ($mail_server_id === null || (is_array($mail_server_id) && count($mail_server_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mail_server_id when calling getListAddressForwarding'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $mail_server_id)) {
            throw new \InvalidArgumentException("invalid value for \"mail_server_id\" when calling ForwardApi.getListAddressForwarding, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        
        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getListAddressForwarding'
            );
        }
        if (!preg_match("/^[0-9a-fA-F]{24}$/", $account_id)) {
            throw new \InvalidArgumentException("invalid value for \"account_id\" when calling ForwardApi.getListAddressForwarding, must conform to the pattern /^[0-9a-fA-F]{24}$/.");
        }
        

        $resourcePath = '/api/v1/mails/{mailServerID}/accounts/{accountID}/forwards';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($mail_server_id !== null) {
            $resourcePath = str_replace(
                '{' . 'mailServerID' . '}',
                ObjectSerializer::toPathValue($mail_server_id),
                $resourcePath
            );
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'accountID' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
