<?php
/**
 * GetMetricsSummary200ResponseDataMetricsTotolObjectsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Object Storage API Documentaion
 *
 * A scalable, reliable, and cost effective Object Storage solution to support your application from liara-cloud
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@liara.ir
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetMetricsSummary200ResponseDataMetricsTotolObjectsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetMetricsSummary200ResponseDataMetricsTotolObjectsInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetMetricsSummary200ResponseDataMetricsTotolObjectsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetMetricsSummary200ResponseDataMetricsTotolObjectsInner"
     */
    public function testGetMetricsSummary200ResponseDataMetricsTotolObjectsInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
