<?php
/**
 * Mail
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Liara Mail API Documentation
 *
 * A fully featured mail delivery platform for incoming & outgoing e-mail
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@liara.ir
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
;
namespace OpenAPI\Client;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\Api\AccountsApi;
use OpenAPI\Client\Api\AttachmentsApi;
use OpenAPI\Client\Api\EventApi;
use OpenAPI\Client\Api\ForwardApi;
use OpenAPI\Client\Api\InboundrulesApi;
use OpenAPI\Client\Api\MailsApi;
use OpenAPI\Client\Api\MessagesApi;
use OpenAPI\Client\Api\SmtpApi;

/**
 * Mail Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Mail
{
    public Configuration $mailConfig;
    public MailsApi $MailsApi;
    public InboundrulesApi $InboundrulesApi;
    public SmtpApi $SmtpApi;
    public AccountsApi $AccountsApi;
    public MessagesApi $MessagesApi;
    public ForwardApi $ForwardApi;
    public AttachmentsApi $AttachmentsApi;
    public EventApi $EventApi;

    public function __construct(string $token)
    {
        $this->mailConfig = Configuration::getDefaultConfiguration()
            ->setApiKey("Authorization", "Bearer $token")
            ->setHost("https://mail-service.iran.liara.ir");

        $this->MailsApi = new MailsApi(null, $this->mailConfig);
        $this->InboundrulesApi = new InboundrulesApi(null, $this->mailConfig);
        $this->SmtpApi = new SmtpApi(null, $this->mailConfig);
        $this->AccountsApi = new AccountsApi(null, $this->mailConfig);
        $this->MessagesApi = new MessagesApi(null, $this->mailConfig);
        $this->ForwardApi = new ForwardApi(null, $this->mailConfig);
        $this->AttachmentsApi = new AttachmentsApi(null, $this->mailConfig);
        $this->EventApi = new EventApi(null, $this->mailConfig);
    }
}