<?php
/**
 * GetDatabaseSummaryReports200ResponseCpuUsageInnerValueInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DBaaS
 *
 * Manage your databases using our API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@liara.ir
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetDatabaseSummaryReports200ResponseCpuUsageInnerValueInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetDatabaseSummaryReports200ResponseCpuUsageInnerValueInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetDatabaseSummaryReports200ResponseCpuUsageInnerValueInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetDatabaseSummaryReports200ResponseCpuUsageInnerValueInner"
     */
    public function testGetDatabaseSummaryReports200ResponseCpuUsageInnerValueInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
